version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 dari kontainer ke host
    environment:
      - HOST=0.0.0.0
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app  # Menyinkronkan folder lokal dengan container, hanya untuk pengembangan
    networks:
      - nextjs_network
    restart: unless-stopped

networks:
  nextjs_network:
    driver: bridge
